In [2]:
import pandas as pd

## Initiate dataframe

In [5]:
df_status=pd.read_csv("statusinvest-busca-avancada.csv", sep=';')

In [6]:
df_status

,TICKER,PRECO,DY,P/L,P/VP,P/ATIVOS,MARGEM BRUTA,MARGEM EBIT,MARG. LIQUIDA,P/EBIT,...,PATRIMONIO / ATIVOS,PASSIVOS / ATIVOS,GIRO ATIVOS,CAGR RECEITAS 5 ANOS,CAGR LUCROS 5 ANOS,LIQUIDEZ MEDIA DIARIA,VPA,LPA,PEG Ratio,VALOR DE MERCADO
0,A,"107,76","0,84","27,83","5,67","2,95","50,93","21,02","16,20","18,00",...,"0,52","0,48","0,66","8,90","12,89",NaN,"19,00","3,87",NaN,"31.529.207.448,00"
1,AA,"24,71","1,62","-4,92","0,98","0,32","5,98","-6,05","-8,44","-169,62",...,"0,32","0,68","0,76","1,34",NaN,NaN,"25,26","-5,02",NaN,"4.410.040.649,00"
2,AACG,"0,87",NaN,"-2,65","1,20","0,38","51,68","-31,49","-32,34",NaN,...,"0,32","0,68","0,44","106,31",NaN,NaN,"0,72","-0,33",NaN,"27.479.733,00"
3,AACQ,"9,99",NaN,"-93,43","180,94","1,25",NaN,NaN,NaN,NaN,...,"0,01","0,12","0,00",NaN,NaN,NaN,"0,06","-0,11",NaN,"904.719.375,00"
4,AACQU,"11,05",NaN,"-103,35","200,14","1,38",NaN,NaN,NaN,NaN,...,"0,01","0,12","0,00",NaN,NaN,NaN,"0,06","-0,11",NaN,"904.719.375,00"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6169,ZUO,"7,90",NaN,"-5,94","9,85","1,63","63,04","-38,05","-44,97","-9,28",...,"0,17","0,83","0,61","18,28",NaN,NaN,"0,80","-1,33",NaN,"1.109.950.000,00"
6170,ZVO,"0,09",NaN,"-0,08","0,47","0,04","35,09","-17,75","-17,80","-0,09",...,"0,08","0,92","2,69","-12,86",NaN,NaN,"0,19","-1,20",NaN,"3.078.549,00"
6171,ZYME,"7,30",NaN,"3,02","1,14","0,85","100,00","40,70","37,58","2,62",...,"0,75","0,25","0,75","51,45",NaN,NaN,"6,41","2,42",NaN,"511.014.600,00"
6172,ZYNE,"1,30",NaN,"-1,87","2,42","1,73",NaN,NaN,NaN,"-1,88",...,"0,72","0,28","0,00",NaN,NaN,NaN,"0,54","-0,70",NaN,"70.121.220,00"
6173,ZYXI,"8,94",NaN,"18,98","5,17","2,00","79,83","11,40","8,59","12,08",...,"0,39","0,61","1,23","46,51","18,28",NaN,"1,73","0,47",NaN,"303.066.000,00"

In [ ]:
risk=0.131

Bazin=DPA/0.06

if VPA>0 and LPA>0:
    Graham=(22,5*LPA*VPA)^0.5

crescimento_esperado=(1-Payout)*ROE

if CAGR LUCRO 5A==0:
    media_crescimento=crescimento_esperado
elif crescimento_esperado==0:
    media_crescimento=CAGR LUCRO 5
else:
    media_crescimento=(crescimento_esperado+CAGR LUCRO5A)/2

if D1>0:
    D1=DPA*(1+CAGR LUCRO 5A)

Gordon = D1/(risk-CAGR LUCRO5A)